version: '2'
services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    ports: 
      - "5434:5432"
    networks: 
      - docker
  keycloak:
    image: jboss/keycloak
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports: 
      - "8080:8080"
    networks: 
      - docker

networks: 
  docker:
    driver: bridge